openapi: 3.0.0
info:
  title: Hospital Digital Marketing Task Tracker API
  version: 1.0.0
  description: API documentation for managing daily digital marketing tasks of hospital executives.

servers:
  - url: http://localhost:3000/api

paths:
  /executives:
    post:
      summary: Create a new executive
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
      responses:
        '201':
          description: Executive created
        '400':
          description: Invalid input
    get:
      summary: List all executives
      responses:
        '200':
          description: List of executives
        '500':
          description: Server error

  /executives/{id}:
    get:
      summary: Get executive by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: UUID of the executive
      responses:
        '200':
          description: Executive details
        '404':
          description: Executive not found

    patch:
      summary: Update an executive
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: UUID of the executive
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
      responses:
        '200':
          description: Executive updated
        '400':
          description: Update failed

    delete:
      summary: Delete an executive
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Executive deleted
        '400':
          description: Delete failed

  /tasks/today/{executiveId}:
    get:
      summary: Get today's tasks for a specific executive
      parameters:
        - in: path
          name: executiveId
          required: true
          schema:
            type: string
          description: UUID of the executive
      responses:
        '200':
          description: List of today's tasks
        '500':
          description: Server error

  /tasks/date/{date}/{executiveId}:
    get:
      summary: Get tasks by date for a specific executive
      parameters:
        - in: path
          name: date
          required: true
          schema:
            type: string
            format: date
          description: Date in YYYY-MM-DD format
        - in: path
          name: executiveId
          required: true
          schema:
            type: string
          description: UUID of the executive
      responses:
        '200':
          description: List of tasks for the date
        '500':
          description: Server error

  /tasks/update/{taskId}:
    patch:
      summary: Update task status, comment, hours, etc.
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
          description: UUID of the task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [not_started, in_progress, done]
                comment:
                  type: string
                comment_tag:
                  type: string
                actual_hours:
                  type: number
      responses:
        '200':
          description: Task updated successfully
        '500':
          description: Server error

  /tasks/upload/{taskId}:
    post:
      summary: Upload a proof file for a task
      parameters:
        - in: path
          name: taskId
          required: true
          schema:
            type: string
          description: UUID of the task
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Upload successful
        '400':
          description: No file uploaded
        '500':
          description: Upload failed

  /tasks/executives/{id}/performance-summary:
    get:
      summary: Get performance summary of an executive
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Executive UUID
      responses:
        '200':
          description: Summary of tasks, completion %, and avg hours
        '500':
          description: Server error
